### ISSUE TITLE
crash in `on_place` with technic cables (pointed_thing issue)

### ISSUE THREAD

**Issue by BuckarooBanzay** [SwissalpS/replacer#32]
Backtrace
```
2022-01-13 12:00:14: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'blockexchange' in callback item_OnUse(): ...//worldmods/technic/technic/machines/register/cables.lua:95: table index is nil
2022-01-13 12:00:14: ERROR[Main]: stack traceback:
2022-01-13 12:00:14: ERROR[Main]: 	...//worldmods/technic/technic/machines/register/cables.lua:95: in function 'on_place'
2022-01-13 12:00:14: ERROR[Main]: 	/data/world//worldmods/replacer/replacer.lua:230: in function 'replace_single_node'
2022-01-13 12:00:14: ERROR[Main]: 	/data/world//worldmods/replacer/replacer.lua:323: in function </data/world//worldmods/replacer/replacer.lua:268>
```

Looks like the on_place has a pointed_thing with same above and below vectors:
* https://github.com/SwissalpS/replacer/blob/94fc003fd000945ffc7f930e3257f642ea22d121/replacer.lua#L230
* https://github.com/mt-mods/technic/blob/master/technic/machines/register/cables.lua#L87 (calculation fails here)

Not sure where this should be fixed here or in the `technic` mod but above and below with the same positions sounds wrong somehow :shrug:

**Comment by OgelGames** [comment]
Fixed here: https://github.com/mt-mods/technic/commit/7e466e9b41215306b220d83b932b754294f32e1d

> Not sure where this should be fixed here or in the technic mod but above and below with the same positions sounds wrong somehow 🤷

I think that's intentional:
https://github.com/SwissalpS/replacer/blob/d4374109b390bf27446407fd329486b4e3ac9bc4/replacer.lua#L228-L231

**Comment by S-S-X** [comment]
> Not sure where this should be fixed here or in the `technic` mod but above and below with the same positions sounds wrong somehow 🤷

I think above and below can be at same position in one special case: player is is inside target node.
Taking that into account I think it is not really that wrong to have equal above and under but replacer could still use real pointed_thing for technic cables to allow copying cable plate orientation.

**Comment by SwissalpS** [comment]
are there any other nodes that work similarly? (apart from seeds)

**Comment by SwissalpS** [comment]
I've been hesitant to add a special case for technic cables as it's the cables that do something different than nodes generally do.

**Comment by S-S-X** [comment]
> I've been hesitant to add a special case for technic cables as it's the cables that do something different than nodes generally do.

If you would build actual pointed_thing then it would work same for every possible node but any special case would still need special handling because with custom implementations it is very likely that function is different and if it is used for orientation then that will also be different.
For example technic cable plates have 2 different outcomes for exact same pointed_thing depending on player controls.

Basically: there's no way to use generic code for custom placement.

However with some hacks you could build semi-generic code that uses either whitelist or blacklist to include / exclude nodes that use pointed_thing only for orientation and orientation wont actually change outcome. This is the case with cable plates: those can be placed with any orientation and node swapped to originally cloned node afterwards.

Or alternatively you could allow mod to override replacer data when node is copied to replacer memory, that allows having optional generic callback to handle special cases in other mods without adding node specific support into replacer mod.

**Comment by SwissalpS** [comment]
closing as ideas mentioned here have been implemented in https://github.com/SwissalpS/replacer/pull/33
