### ISSUE TITLE
changing mode is cumbersome

### ISSUE THREAD

**Issue by SwissalpS** [SwissalpS/replacer#6]
Let's use special+right-click to open a formspec with buttons to quickly switch modes.

**Comment by SwissalpS** [comment]
Have added a formspec to change mode. It can be triggered by special(fast)+right-click on a node
and special(fast)+left-click anywhere including air.
[The branch is formspecModeChange](https://github.com/SwissalpS/replacer/tree/formspecModeChange)
I appreciate test-reports and comments before I merge the changes into master.

@coil0 @6r1d @S-S-X @OgelGames @BuckarooBanzay @HybridDog @Sokomine @int-ua

**Comment by OgelGames** [comment]
Nice, works perfectly 👍

**Comment by S-S-X** [comment]
Works well but few things I would like to be changed a bit:

1. Do not hide button for mode that is in use, instead use some other indication for selected mode like background color / button color / add some markers to text like "> crust <" etc. or even set it as plain label if there's some problem with buttons.

2. Now there's 2 triggers for form, I'd say it would be better to keep old special + rmb trigger for cycling modes because it is a lot faster and wont cause interrupts. Small thing but very good shortuct and feels like very big and annoying change after you've learned fast way to cycle modes,

**Comment by SwissalpS** [comment]
thanks SX, once again very good input :D

**Comment by SwissalpS** [comment]
[I'm quite happy with this state 7a41f02](https://github.com/SwissalpS/replacer/tree/7a41f0278a8f35ae65d5fcd8fa538072afe27aaa)

**Comment by S-S-X** [comment]
Didn't find any new problems, I'd say this is good enough for pr+merge.

Unless you want to start fixing old issues, that one mode marked as "TODO" in chat message can be selected via sepcial + rmb.
Form also works well enough there as it does not "highlight" any of the selections.

I'd say open another issue for this one, it was already there before these changes.

**Comment by SwissalpS** [comment]
Yes, I kept mode 4 TODO in as reminder and agree totally separate issue.
