### ISSUE TITLE
Implement mode 4, chunkborder, or drop it.

### ISSUE THREAD

**Issue by SwissalpS** [SwissalpS/replacer#8]
I don't know what it is supposed to do :/

**Comment by S-S-X** [comment]
maybe replace border of chunk? or build to border of chunk depending on function used.

**Comment by SwissalpS** [comment]
I don't understand what chunk refers to, can't be mapgen chunks meant.

**Comment by S-S-X** [comment]
I'm thinking of chunk of blocks, it has borders around that chunk. Border is where there is different block type at same level with blocks pointed with replacer.
It is basically very similar to field mode but only operates on borders of area, I think that can be useful for many different things.

**Comment by thomasrudin** [comment]
Hmm, that was originally implemented by @coil0 if i remember correctly...

**Comment by SwissalpS** [comment]
actually @HybridDog was the one that added modes for creative. @coil0 made the modes available as technic tool.

**Comment by SwissalpS** [comment]
> why is this a fork of a fork again

@Sokomine's version went stale, I merged it with @HybridDog's version on your suggestion and based it on @coil0's version to include his fixes.

**Comment by HybridDog** [comment]
I'm unsure about what I wanted to implement for the chunkborder mode. Iirc, I tried to implement something which is very similar to crust mode:
![chunkborder_maybe](https://user-images.githubusercontent.com/3192173/74017493-a1659d00-4994-11ea-9e21-589a9a53987c.png)
Since light does no longer go through invisible diagonal edges in Minetest, this mode would not be needed. I probably did not implement it because crust is usually sufficient.

Fyi: The algorithms are implemented with Flood Fill. sofar et al. created a faster algorithm, which is currently used for falling nodes; there is an untested generalized version: https://github.com/HybridDog/vector_extras/blob/9c6e53dd0a553a26fd451a88ec800cb23431243a/fill_3d.lua

I've made a description of the replacer modes with pictures:

## Replacer Modes

Situation: the player points at a node and wants to use the replacer. <br/>
* Bright blue: the ray of sight and pointed thing above and under
* Different nodes:
  * White: air
  * Dark grey: a solid node which should be replaced
  * Brown: another solid node adjacent to the grey one
  * Yellow green: a translucent node, such as leaves or glass
  * Red (in later pictures): the node which the replacer (re)places
* The black thing: it should depict an eye for the camera position.
![replacer_template](https://user-images.githubusercontent.com/3192173/74016149-36b36200-4992-11ea-86d1-2d3b64035557.png)



### Single Mode

Left click: 
![replacer_single_leftclick](https://user-images.githubusercontent.com/3192173/74015937-e1775080-4991-11ea-912b-4f4e75c53918.png)

Right click:
![replacer_single_rightclick](https://user-images.githubusercontent.com/3192173/74015939-e20fe700-4991-11ea-9e4d-8f8c8900024d.png)

### Field Mode

The replacer changes nodes in a 2D slice (it is 1D in these illustrations).
Left click:
![replacer_field_leftclick](https://user-images.githubusercontent.com/3192173/74015955-e63c0480-4991-11ea-95b9-4b312bc62ed1.png)
Right click:
![replacer_field_rightclick](https://user-images.githubusercontent.com/3192173/74015933-e0deba00-4991-11ea-8321-de9c0499dcf3.png)

### Crust Mode

Left click: the replacer changes visually adjacent nodes (of the same type) on a surface
![replacer_crust_leftclick](https://user-images.githubusercontent.com/3192173/74015951-e5a36e00-4991-11ea-8cdf-f8b1c8897da9.png)

Right click: the replacer places nodes onto the surface so that the surface below it is hidden; the added crust can be bounded by other solid nodes but not translucent nodes
![replacer_crust_rightclick](https://user-images.githubusercontent.com/3192173/74015954-e63c0480-4991-11ea-956c-ee6848c182be.png)

**Comment by SwissalpS** [comment]
@HybridDog thanks very much for the explanations and pointers.

> I probably did not implement it because crust is usually sufficient.
Agree, have not run into situations where field or crust didn't solve my needs.
I mostly use field.

**Comment by SwissalpS** [comment]
we removed it -> done.
